name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  goVersion: 1.25

jobs:
  test-unit:
    name: test-unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.goVersion }}
      - uses: actions/checkout@v5
      - run: make test/unit
  
  test-integration:
    name: test-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.goVersion }}
      - uses: actions/checkout@v5
      - run: make test/coverage

  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v5
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.txt
